version: "2"
services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - zveno

  postgresql:
    image: "postgres:12.1"
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_DB=mybase
      - POSTGRES_USER=alekspavlik
      - POSTGRES_PASSWORD=nothing
    networks:
      - zveno

  adminer:
      image: "adminer:4.7.5"
      ports:
        - "8082:8080"
      networks:
        - zveno
networks:
  zveno: